Miniprojrect/Models/ProjectIngredient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Miniprojrect.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectIngredient
{

    public int IngredientID { get; set; }

    public string IngredientName { get; set; }

    public Nullable<decimal> Price { get; set; }

    public string ImageURL { get; set; }

    public Nullable<int> CategoryID { get; set; }



    public virtual ProjectCategory ProjectCategory { get; set; }

}

}

Miniprojrect/Controllers/ProjectIngredientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Miniprojrect.Models;

namespace Miniprojrect.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProjectIngredientsController : Controller
    {
        private Training_12DecMumbaiEntities3 db = new Training_12DecMumbaiEntities3();

        // GET: ProjectIngredients
        public ActionResult Index()
        {
            //var projectIngredients = db.ProjectIngredients.Include(p => p.ProjectCategory);
            //return View(projectIngredients.ToList());
            return View();
        }

        public ActionResult FileUpload(HttpPostedFileBase file)
        {
            if (file != null)
            {
                string ImageName = System.IO.Path.GetFileName(file.FileName);
                string physicalPath = Server.MapPath("~/Image/" + ImageName);
                    
                // save image in folder
                file.SaveAs(physicalPath);

                //save new record in database
                ProjectIngredient newRecord = new ProjectIngredient();

                newRecord.IngredientID = Convert.ToInt32(Request.Form["PizzaID"]);
                newRecord.IngredientName = Request.Form["PName"];
                newRecord.ImageURL = ImageName;
                //newRecord.Category = Request.Form["Category"];
                newRecord.Price = Convert.ToInt32(Request.Form["Price"]);
                db.ProjectIngredients.Add(newRecord);
                db.SaveChanges();

            }
            //Display records
            return RedirectToAction("../ProjectIngredients/Display1");
        }

        public ActionResult Display1()
        {
            return View();
        }

       

        //// GET: ProjectIngredients/Delete/5
        //public ActionResult Delete()
        //{
           
        //    return View();
        //}

        //// POST: ProjectIngredients/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed()
        //{
        //    ProjectIngredient newRecord = new ProjectIngredient();

        //    newRecord.IngredientID = Convert.ToInt32(Request.Form["IID"]);
        //    newRecord.IngredientName = Request.Form["IName"];
        //    newRecord.ImageURL = Request.Form["iImage"]; 
        //    //newRecord.Category = Request.Form["Category"];
        //    newRecord.Price = Convert.ToInt32(Request.Form["Price"]);
        //    db.ProjectIngredients.Remove(newRecord);
        //    db.SaveChanges();

            
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Miniprojrect/Views/ProjectIngredients/Delete.cshtml
@model Miniprojrect.Models.ProjectIngredient

@{
}

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>ProjectIngredient</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.IngredientID)
            </dt>

            <dd>
                @Html.TextBox("IID")
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.IngredientName)
            </dt>

            <dd>
                @Html.TextBox("IName")
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.TextBox("Price")
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ImageURL)
            </dt>

            <dd>
                @Html.TextBox("iImage")
            </dd>

        </dl>
    
        @using (Html.BeginForm("DeleteConfirmed", "ProjectIngredients", FormMethod.Post,
                    new { enctype = "multipart/form-data" })) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

Miniprojrect/Views/ProjectIngredients/Display1.cshtml
@using Miniprojrect.Models;
@{
    ViewBag.Title = "Display1";
}
@{
    Training_12DecMumbaiEntities3 db = new Training_12DecMumbaiEntities3();
}
<table border="1">
    <thead>
        <tr>
            <th>Ingredient Name</th>
            <th>ImageURL</th>
            <th>Image</th>
          
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in db.ProjectIngredients)
        {
            <tr>

                <td>@item.IngredientName</td>
                <td>@item.ImageURL</td>
                <td><img src="~/Image/@item.ImageURL" width="100" height="100" /></td>
                @*<td>@item.CategoryID</td>*@
                <td>@item.Price</td>
            </tr>
            
        }
    </tbody>
</table>

Miniprojrect/Views/ProjectIngredients/Index.cshtml
@*@model IEnumerable<Miniprojrect.Models.ProjectIngredient>

    @{

    }

    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Index</title>
    </head>
    <body>
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IngredientName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageURL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageURL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProjectCategory.CategoryName)
                </th>
                <th></th>
            </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IngredientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImageURL)
                </td>
                <td>
                    <img src="~/Image/@item.ImageURL" width="100" height="100" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectCategory.CategoryName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.IngredientID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.IngredientID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.IngredientID })
                </td>
            </tr>
        }

        </table>
    </body>
    </html>*@


@model IEnumerable<Miniprojrect.Models.ProjectIngredient>
@{
    ViewBag.Title = "Index1";
}
<br /> <br />
@using (Html.BeginForm("FileUpload", "ProjectIngredients", FormMethod.Post,
                    new { enctype = "multipart/form-data" }))

{
    <div>
        Ingredient Name<br />
        @Html.TextBox("PName") <br />
        Image<br />
        <input type="file" name="file" id="file" style="width: 100%;" /> <br />
        <input type="submit" value="Upload" class="submit" /> <br />
        @*Category<br />
            @Html.TextBox("Category") <br />*@
        Price<br />
        @Html.TextBox("Price") <br />
    </div>
}